spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/normal?characterEncoding=utf8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&useSSL=false
    username: admin
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
  redis:
    port: 6379
    database: 0
    host: 127.0.0.1
    password: dongdong1
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 5000ms
server:
  port: 443
  ssl:
    key-store: classpath:2893913_xbleey.cn.pfx
    key-store-password: f7UdHUdi
    key-store-type: PKCS12